name: flutter_openssl_crypto
description: libcrypto from OpenSSL for Android and iOS to be used with dart:ffi
version: 0.5.0
repository: https://github.com/famedly/flutter_openssl_crypto
issue_tracker: https://github.com/famedly/flutter_openssl_crypto/issues

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.famedly.flutter_openssl_crypto
        pluginClass: FlutterOpensslCryptoPlugin
      ios:
        pluginClass: FlutterOpensslCryptoPlugin
      macos:
        pluginClass: FlutterOpensslCryptoPlugin
